### PR TITLE
Feature spectral radius

### PR DESCRIPTION
**Pull request by tpoisot**
# Add the spectral radius

This adds a function to measure the spectral radius of a network. For bipartite networks, this involves transforming them into a unipartite version.
## Related issues

When merged, solves #147 (which is already closed) 

## Checklist

- [x] The code is covered by unit tests
  - [x] Additional cases or module in `test/...`
  - [x] Relevant lines in `test/runtests.jl`
- [x] The code is *documented*
  - [x] Docstrings written for every function
  - [x] If needed, additional lines in `docs/src/...`
- [x] All contributors have added their name and affiliation to `.zenodo.json`

## Pinging

Pinging @tpoisot and @taddallas

### CODE REVIEW

**Comment by taddallas** [comment]
Alright. So the issue is that the spectral radius is dependent on matrix size, and that it is a quantity calculated on the adjacency matrix (n+m x n+m) of the bipartite graph instead of the interaction matrix (n x m). 

To the first point, using the norm seems reasonable to me. I'll try to read up on it and see if there's some precedent for this. It's not like a null approach would work, as any transformation which maintains the number of interactions per species would give the same spectral radius. Is there a good citation demonstrating the spectral radius to be sensitive to matrix size? For some reason, I thought it's lack of sensitivity was a selling point. 

To the second point, ja.

**Comment by taddallas** [comment]
Can confirm sensitivity. 

```
ret <- c()
nodez <- 10:200

for(i in 1:length(nodez)){
	g <- sample_bipartite(nodez[i], 5, p=.1)
	A <- as_adjacency_matrix(g)
	ret[i] <- Re(eigen(A)$value[1])
}
```

**Comment by tpoisot** [comment]
[Philips](https://www.sciencedirect.com/science/article/pii/S1476945X11000614) has a formula for the maximal spectral radius, which accounts for both the number of nodes and the number of edges. Then again, [SK&A](https://www.nature.com/articles/ncomms2422) use a different upper bound in the supp mat.

So what I've done is to implement both as functions that can be given as arguments to `ρ`. Let me know if this works for you, and then I'll merge and tag a new release.

**Comment by tpoisot** [comment]
FYI, I have limited the code to binary matrices, as the upper bounds are not really clear for other type of information. I've also added the tests based on the values in Figure 1 of SK&A2013, and it's all good. This one is ready to merge.

**Pull request merged**
